f1=input("Enter Fruit Number 1 : ")
f2=input("Enter Fruit Number 2 : ")
f3=input("Enter Fruit Number 3 : ")
f4=input("Enter Fruit Number 4 : ")
f5=input("Enter Fruit Number 5 : ")
f6=input("Enter Fruit Number 6 : ")
f7=input("Enter Fruit Number 7 : ")
MyFruitList=[f1,f2,f3,f4,f5,f6,f7]
print(MyFruitList)

m1=input("Enter the mark of student 1")
m2=input("Enter the mark of student 2")
m3=input("Enter the mark of student 3")
m4=input("Enter the mark of student 4")
m5=input("Enter the mark of student 5")
m6=input("Enter the mark of student 6")
m1=int(m1)
m2=int(m2)
m3=int(m3)
m4=int(m4)
m5=int(m5)
m6=int(m6)
marks=[m1,m2,m3,m4,m5,m6]
marks.sort()
print(marks)